module.exports = {
  OPEN: 'OPEN',
  PIN_OK: 'PIN_OK',
  PIN_FAIL: 'PIN_FAIL',
  VIEW: 'VIEW',
  DOWNLOAD: 'DOWNLOAD',
  ZIP_DOWNLOAD: 'ZIP_DOWNLOAD',
  DENY_EXPIRED: 'DENY_EXPIRED',
  DENY_REVOKED: 'DENY_REVOKED',
  DENY_LIMIT: 'DENY_LIMIT',
  REVOKE: 'REVOKE'
};
